### ISSUE TITLE
Create a User system

### ISSUE THREAD

**Issue by threezool** [SavelyAB/Savely-Web#2]
The user system needs to handle users in two ways, as a child and as a parent and those can be paired to each other.

- [ ] A child can create a account
- [ ] A Parent can create a account
- [ ] A parent can connect a child and vice versa
- [ ] A user can be authenticated
- [ ] A user gets its user information once authenticated
